question_data = [{"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                  "text": "The Great Wall of China is visible from the moon.", "answer": "False",
                  "incorrect_answers": ["True"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                  "text": "Video streaming website YouTube was purchased in it&#039;s entirety by"
                          "Facebook for US$1.65 billion in stock.",
                  "answer": "False", "incorrect_answers": ["True"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
                  "text": "&quot;Typewriter&quot; is the longest word that can be typed using o"
                          "nly the first row on a QWERTY keyboard.",
                  "answer": "True", "incorrect_answers": ["False"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
                  "text": "Coca-Cola&#039;s original colour was green.", "answer": "False",
                  "incorrect_answers": ["True"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
                  "text": "The US emergency hotline is 911 because of the September 11th terrorist"
                          " attacks.",
                  "answer": "False", "incorrect_answers": ["True"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                  "text": "French is an official language in Canada.", "answer": "True",
                  "incorrect_answers": ["False"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "hard",
                  "text": "This is the correct spelling of &quot;Supercalifragilisticexpialidocious&quot;.",
                  "answer": "True", "incorrect_answers": ["False"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                  "text": "It is automatically considered entrapment in the United States if the police sell you illegal substances without revealing themselves.",
                  "answer": "False", "incorrect_answers": ["True"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
                  "text": "The sum of all the numbers on a roulette wheel is 666.", "answer": "True",
                  "incorrect_answers": ["False"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
                  "text": "Furby was released in 1998.", "answer": "True", "incorrect_answers": ["False"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                  "text": "Nutella is produced by the German company Ferrero.", "answer": "False",
                  "incorrect_answers": ["True"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
                  "text": "An eggplant is a vegetable.", "answer": "False", "incorrect_answers": ["True"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
                  "text": "The bikini is named after the &quot;Bikini Atoll&quot;, an island where the United States conducted tests on atomic bombs.",
                  "answer": "True", "incorrect_answers": ["False"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
                  "text": "Cucumbers are usually more than 90% water.", "answer": "True",
                  "incorrect_answers": ["False"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                  "text": "Bulls are attracted to the color red.", "answer": "False",
                  "incorrect_answers": ["True"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
                  "text": "You are allowed to sell your soul on eBay.", "answer": "False",
                  "incorrect_answers": ["True"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "hard",
                  "text": "&quot;Number 16 Bus Shelter&quot; was a child&#039;s name that was approved by the New Zealand government.",
                  "answer": "True", "incorrect_answers": ["False"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                  "text": "&quot;Ananas&quot; is mostly used as the word for Pineapple in other languages.",
                  "answer": "True", "incorrect_answers": ["False"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                  "text": "The Sun rises from the North.", "answer": "False",
                  "incorrect_answers": ["True"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                  "text": "The color orange is named after the fruit.", "answer": "True",
                  "incorrect_answers": ["False"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                  "text": "You can legally drink alcohol while driving in Mississippi.", "answer": "True",
                  "incorrect_answers": ["False"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
                  "text": "The term &quot;Spam&quot; came before the food product &quot;Spam&quot;.",
                  "answer": "False", "incorrect_answers": ["True"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                  "text": "On average, at least 1 person is killed by a drunk driver in the United States every hour.",
                  "answer": "True", "incorrect_answers": ["False"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                  "text": "In 2010, Twitter and the United States Library of Congress partnered together to archive every tweet by American citizens.",
                  "answer": "True", "incorrect_answers": ["False"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
                  "text": "Kissing someone for one minute burns about 2 calories.", "answer": "True",
                  "incorrect_answers": ["False"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
                  "text": "Sitting for more than three hours a day can cut two years off a person&#039;s life expectancy.",
                  "answer": "True", "incorrect_answers": ["False"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
                  "text": "The French word to travel is &quot;Travail&quot;", "answer": "False",
                  "incorrect_answers": ["True"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                  "text": "Pluto is a planet.", "answer": "False", "incorrect_answers": ["True"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                  "text": "Adolf Hitler was born in Australia. ", "answer": "False",
                  "incorrect_answers": ["True"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                  "text": "When you cry in space, your tears stick to your face.", "answer": "True",
                  "incorrect_answers": ["False"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
                  "text": "The French word for &quot;glass&quot; is &quot;glace&quot;.", "answer": "False",
                  "incorrect_answers": ["True"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                  "text": "The Lego Group was founded in 1932.", "answer": "True",
                  "incorrect_answers": ["False"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                  "text": "One of Donald Trump&#039;s 2016 Presidential Campaign promises was to build a border wall between the United States and Mexico.",
                  "answer": "True", "incorrect_answers": ["False"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                  "text": "Romanian belongs to the Romance language family, shared with French, Spanish, Portuguese and Italian. ",
                  "answer": "True", "incorrect_answers": ["False"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
                  "text": "Albert Einstein had trouble with mathematics when he was in school.",
                  "answer": "False", "incorrect_answers": ["True"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
                  "text": "Fast food restaurant chains Carl&#039;s Jr. and Hardee&#039;s are owned by the same company.",
                  "answer": "True", "incorrect_answers": ["False"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "hard",
                  "text": "Stagecoach owned &quot;South West Trains&quot; before losing the rights to FirstGroup and MTR in March of 2017.",
                  "answer": "True", "incorrect_answers": ["False"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
                  "text": "&quot;Santa Claus&quot; is a variety of melon.", "answer": "True",
                  "incorrect_answers": ["False"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                  "text": "&quot;27 Club&quot; is a term used to refer to a list of famous actors, musicians, and artists who died at the age of 27.",
                  "answer": "True", "incorrect_answers": ["False"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                  "text": "Scotland voted to become an independent country during the referendum from September 2014.",
                  "answer": "False", "incorrect_answers": ["True"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "hard",
                  "text": "Spoon theory is a theory, utilizing &quot;Spoons&quot; as a metaphor for energy they can use in a day.",
                  "answer": "True", "incorrect_answers": ["False"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                  "text": "The National Animal of Scotland is the Unicorn.", "answer": "True",
                  "incorrect_answers": ["False"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
                  "text": "Haggis is traditionally ate on Burns Night.", "answer": "True",
                  "incorrect_answers": ["False"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
                  "text": "Francis Bacon died from a fatal case of pneumonia while he was attempting to preserve meat by stuffing a chicken with snow.",
                  "answer": "True", "incorrect_answers": ["False"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
                  "text": "The British organisation CAMRA stands for The Campaign for Real Ale.",
                  "answer": "True", "incorrect_answers": ["False"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
                  "text": "The commercial UK channel ITV stands for &quot;International Television&quot;.",
                  "answer": "False", "incorrect_answers": ["True"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                  "text": "Vietnam&#039;s national flag is a red star in front of a yellow background.",
                  "answer": "False", "incorrect_answers": ["True"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                  "text": "A pasodoble is a type of Italian pasta sauce.", "answer": "False",
                  "incorrect_answers": ["True"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
                  "text": "&quot;Buffalo buffalo Buffalo buffalo buffalo buffalo Buffalo buffalo.&quot; is a grammatically correct sentence.",
                  "answer": "True", "incorrect_answers": ["False"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                  "text": "Slovakia is a member of European Union-", "answer": "True",
                  "incorrect_answers": ["False"]}]
